apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "netgpu1" },
            { "name": "netgpu2" }
    ]'
spec:
  containers:
  - image: shaharklein/ub-gen:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
