apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: netgpu2
spec:
  config: '{
    "type": "ovn-k8s-cni-overlay",
    "name": "ovn-kubernetes",
    "network-name": "netgpu2"
  }'
