apiVersion: v1
kind: Pod
metadata:
  name: pod1-gpu00
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "netgpu1" },
    ]'
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: pod1-gpu00

