apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "mode" : "sriov",
        "pfNetdevices": [ "enp5s0", "enp12s0", "enp132s0", "enp139s0" ],
        "devmode" : "switchdev"

    }
