apiVersion: v1
kind: Pod
metadata:
  name: ub-pod
  labels:
    app: ub-pod
spec:
  containers:
  - image: shaharklein/ub-gen:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ub-pod
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
