apiVersion: v1
kind: Pod
metadata:
  name: ub-pod
  labels:
    app: ub-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "netgpu1" },
            { "name": "netgpu2" },
            { "name": "netgpu3" },
            { "name": "netgpu4" }
    ]'
spec:
  containers:
  - image: shaharklein/ub-gen:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ub-pod
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
