apiVersion: apps/v1
kind: Deployment
metadata:
  name: ub-mofed-deployment
  labels:
    app: ub-mofed
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ub-mofed
  template:
    metadata:
      labels:
        app: ub-mofed
      annotations:
        cni: "ovn-k8s-cni-overlay,sriov,sriov,sriov,sriov"
    spec:
      containers:
      - name: ub-mofed
        image: shaharklein/ub-mofed:latest
        securityContext:
          privileged: true
        resources:
          limits:
            rdma/vhca: 1
        command:
        - sh
        - -c
        - |
          ls -l /dev/infiniband /sys/class/net
          sleep 1000000

